---
- name: Testing andrewrothstein.flannel
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'flanneld --version'
      ansible.builtin.command: /usr/local/bin/flanneld --version
      changed_when: false
      register: flanneld_test_output
    - name: Output of 'flanneld --version'
      ansible.builtin.debug:
        msg: '{{ flanneld_test_output.stderr }}'
