---
- name: download flannel
  become: yes
  become_user: root
  get_url:
    url: '{{flannel_url}}'
    dest: '{{flannel_install_dir}}/{{flannel_target}}'
    mode: '0755'
    timeout: '{{flannel_download_timeout_seconds}}'
    checksum: '{{flannel_checksum}}'

- name: link flanneld
  become: yes
  become_user: root
  file:
    src: '{{flannel_install_dir}}/{{flannel_target}}'
    dest: '{{flannel_install_dir}}/flanneld'
    state: link
