---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Check for flannel installation at {{ flannel_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ flannel_exe }}'
  changed_when: false
  register: flannel_binary
- name: Downloading and installing flannel
  when: not flannel_binary.stat.exists
  block:
    - name: Download {{ flannel_tgz_url }} to {{ flannel_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ flannel_tgz_url }}'
        dest: '{{ flannel_tmp_tgz }}'
        mode: '644'
        timeout: '{{ flannel_download_timeout_seconds }}'
        checksum: '{{ flannel_checksum }}'
    - name: Mkdir {{ flannel_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ flannel_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchive...
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ flannel_tmp_tgz }}'
        dest: '{{ flannel_install_dir }}'
        creates: '{{ flannel_exe }}'
  always:
    - name: Rm {{ flannel_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ flannel_tmp_tgz }}'
        state: absent

- name: Linking {{ flannel_link }} to {{ flannel_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ flannel_exe }}'
    dest: '{{ flannel_link }}'
    state: link
